---
- name: apt-get update
  apt: update_cache=true cache_valid_time=3600
- name: install gdebi
  apt: name=gdebi
- name: Check if slack is installed
  command: dpkg-query -W virtualbox
  register: check_virtualbox
  failed_when: false
  changed_when: false
- name: Download Virtualbox
  get_url:
    url: "{{ virtualbox.deb_url }}"
    dest: /tmp/{{ virtualbox.name }}
  when: check_virtualbox.rc == 1
