- name: install docker
  apt:
    update_cache: yes
    name:
      - docker.io
      - docker-compose
- name: group update
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes
