- name: microsoft key add
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: added vscode list
  apt_repository:
    repo: "{{ item }}"
    state: present
    filename: vscode
  with_items:
    - deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main

- name: Install vscode
  apt:
    name: code
    state: latest
    update_cache: true
